type Staker_AutoCompoundUserSettingChanged {
  id: ID!
  account: String!
  newSelectedCompoundType: BigInt!
}

type Staker_Claimed {
  id: ID!
  account: String!
  token: BigInt!
  amount: BigInt!
}

type Staker_Compound {
  id: ID!
  account: String!
  compoundInitiatedBy: String!
  token: BigInt!
  drgAmount: BigInt!
  usdcAmount: BigInt!
}

type Staker_Deposit {
  id: ID!
  funder: String!
  amount: BigInt!
  pendingDragon: BigInt!
  pendingUSDC: BigInt!
}

type Staker_Discarded {
  id: ID!
  account: String!
  rewardsDragon: BigInt!
  rewardsUSDC: BigInt!
}

type Staker_DragonswapTokenPriceOracleSet {
  id: ID!
  dragonswapTokenPriceOracle: String!
}

type Staker_EnteredWithdrawal {
  id: ID!
  account: String!
  amount: BigInt!
  emergency: Boolean!
}

type Staker_InstantWithdraw {
  id: ID!
  account: String!
  unlockedAmount: BigInt!
  redistributedToStakers: BigInt!
  treasuryFee: BigInt!
  emergency: Boolean!
}

type Staker_MarketplaceFeesSet {
  id: ID!
  marketplaceFeeDragon: BigInt!
  marketplaceFeeUSDC: BigInt!
}

type Staker_MinimumDepositSet {
  id: ID!
  minimumDeposit: BigInt!
}

type Staker_NewOffer {
  id: ID!
  seller: String!
  stake: BigInt!
  price: BigInt!
}

type Staker_OfferRemoved {
  id: ID!
  seller: String!
}

type Staker_OwnershipTransferred {
  id: ID!
  previousOwner: String!
  newOwner: String!
}

type Staker_Purchase {
  id: ID!
  buyer: String!
  seller: String!
  boughtAmount: BigInt!
  price: BigInt!
  feeDragon: BigInt!
  feeUSDC: BigInt!
}

type Staker_RankRequirementsSet {
  id: ID!
  rankRequirements: [BigInt!]!
}

type Staker_RewardsIncreased {
  id: ID!
  t: BigInt!
  amount: BigInt!
}

type Staker_StakeManagerSet {
  id: ID!
  stakeManager: String!
}

type Staker_Swept {
  id: ID!
  token: String!
  to: String!
  amount: BigInt!
}

type Staker_TreasuryFeeSet {
  id: ID!
  treasuryFee: BigInt!
}

type Staker_TreasurySet {
  id: ID!
  treasury: String!
}

type Staker_Withdraw {
  id: ID!
  account: String!
  amount: BigInt!
}

type Staker_WithdrawalPeriodChanged {
  id: ID!
  withdrawalPeriod: BigInt!
}

